name: Test Rebol Whitespacers

on:
  push:
    branches: [
      master
    ]
  pull_request:
    branches: [
      master
    ]
  workflow_dispatch:  # Allows running this workflow manually from Actions tab


jobs:
  test-whitespacers:


    # The whitespace tests are short and quick enough to not be too much of a
    # burden on the world, so go ahead and do run it for the release and debug
    # builds on the main desktop platforms.
    #
    # (Rather than use the automatic-matrix'ing, we go ahead and list them
    # manually, because that makes it easier to tweak specifics if desired.)
    #
    strategy:
      matrix:
        include:  # put in order of visibility importance (shown in UI)

        - os: macos-latest
          checked: false

        - os: windows-latest
          checked: false

        - os: ubuntu-latest
          checked: false

        - os: macos-latest
          checked: true

        - os: windows-latest
          checked: true

        - os: ubuntu-latest
          checked: true


    # https://github.com/actions/virtual-environments#available-environments
    #
    runs-on: ${{ matrix.os }}


    steps:


  #====# CHECKOUT STEPS #=====================================================#


    # GitHub CI checkout on Windows auto translates LF to CR/LF in files:
    #
    # https://github.com/actions/checkout/issues/135
    #
    # However, Ren-C is taking the long view on this and prohibiting CR/LF in
    # source by default.
    #
    # https://forum.rebol.info/t/newlina-non-grata/1207
    # https://forum.rebol.info/t/1264
    #
    - name: Disable LF to CRLF Auto Translation In Git
      if: matrix.os == 'windows-latest'
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf


    # https://github.com/actions/checkout
    #
    - uses: actions/checkout@v2



  #====# INSTALL R3 INTERPRETER #=============================================#


    - name: Download and Cache the Interpreter
      uses: metaeducation/ren-c-action@release
      with:
        checked: ${{ matrix.checked }}


  #====# TEST STEPS #==========================================================#

    # The tests are designed to call QUIT and return 1 status on failure, with
    # 0 returned on success.


    # Ren-C is an aggressively redesigned version of the open-source Rebol
    # R3-Alpha code.  The whitespace script that runs on Ren-C establishes a
    # sort of "domain specific language" for writing "Whitespace-like"
    # interpreters.
    # 
    - name: Ren-C Whitespacer Test
      run: |
        r3 ren-c/whitespace.reb


    # The original Rebol version written circa 2010 ran in the pre-open-source
    # "R3-Alpha" interpreter.  That less interesting version still runs today
    # relatively unchanged under emulation via "Redbol", and is kept around as
    # a test of that emulation.
    #
    - name: Historical Rebol Interpreter Test
      uses: metaeducation/ren-c-action@release
      with:
        checked: ${{ matrix.checked }}
        script: |
          print ["The directory is" what-dir]
          do https://raw.githubusercontent.com/metaeducation/ren-c/master/scripts/redbol.reb
          do %rebol/whitespace.reb
